//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_elso_host.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEloado", ReplyAction="http://tempuri.org/IService1/GetEloadoResponse")]
        WCF_elso_server.Eloado GetEloado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEloado", ReplyAction="http://tempuri.org/IService1/GetEloadoResponse")]
        System.Threading.Tasks.Task<WCF_elso_server.Eloado> GetEloadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEloadoName", ReplyAction="http://tempuri.org/IService1/GetEloadoNameResponse")]
        string GetEloadoName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEloadoName", ReplyAction="http://tempuri.org/IService1/GetEloadoNameResponse")]
        System.Threading.Tasks.Task<string> GetEloadoNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetZeneszam", ReplyAction="http://tempuri.org/IService1/GetZeneszamResponse")]
        WCF_elso_server.Zeneszam GetZeneszam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetZeneszam", ReplyAction="http://tempuri.org/IService1/GetZeneszamResponse")]
        System.Threading.Tasks.Task<WCF_elso_server.Zeneszam> GetZeneszamAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF_elso_host.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_elso_host.ServiceReference1.IService1>, WCF_elso_host.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_elso_server.Eloado GetEloado() {
            return base.Channel.GetEloado();
        }
        
        public System.Threading.Tasks.Task<WCF_elso_server.Eloado> GetEloadoAsync() {
            return base.Channel.GetEloadoAsync();
        }
        
        public string GetEloadoName() {
            return base.Channel.GetEloadoName();
        }
        
        public System.Threading.Tasks.Task<string> GetEloadoNameAsync() {
            return base.Channel.GetEloadoNameAsync();
        }
        
        public WCF_elso_server.Zeneszam GetZeneszam() {
            return base.Channel.GetZeneszam();
        }
        
        public System.Threading.Tasks.Task<WCF_elso_server.Zeneszam> GetZeneszamAsync() {
            return base.Channel.GetZeneszamAsync();
        }
    }
}
